name: ifcbdb
channels:
  - conda-forge
dependencies:
- django
- gunicorn
- psycopg2
- pycrypto
- pip
- celery>4.1
- gdal
- libiconv
- numba
- tiledb=2.2
- gcc>=12.1.10
- pip:
  - pymemcache
  - redis
